### ISSUE TITLE
the game instant crash with the mod radium

### ISSUE THREAD

**Issue by coco875** [Darkorg69/Serene-Seasons-Pams-HarvestCraft-2-Crops-Compat#1]
if you want reproduce the error put your mod with radium and it will instant crash with a log report not complete

**Comment by coco875** [comment]
[latest.log](https://github.com/Darkorg69/Serene-Seasons-Pams-HarvestCraft-2-Crops-Compat/files/10356423/latest.log)
the log in question

**Comment by Darkorg69** [comment]
Serene Seasons is outdated. Update to newest version.

`
[main/ERROR]: Missing or unsupported mandatory dependencies: 	Mod ID: 'sereneseasons', Requested by: 'sereneseasonsphc2crops', Expected range: '[1.18.2-7.0.0.15,)', Actual version: '1.18.2-7.0.0.13'
`

**Comment by coco875** [comment]
![image](https://user-images.githubusercontent.com/59367621/210988784-5a53c7d0-092a-4d85-96da-aaa0e9053b49.png)
the last version in curseforge in release and not in beta is 7.0.0.13

**Comment by coco875** [comment]
but normally forge show a windows to say of update the mod but here not

**Comment by coco875** [comment]
ok you have wright by choosing the last version of serene it fix it so is a issue of radium
